// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VodovozSPB.Models
{
    public partial class Departments
    {
        public Departments()
        {
            Employees = new HashSet<Employees>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? BossId { get; set; }

        public virtual Employees Boss { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}