// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VodovozSPB.Models
{
    public partial class Employees
    {
        public Employees()
        {
            Departments = new HashSet<Departments>();
            Orders = new HashSet<Orders>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string MiddleName { get; set; }
        [Column(TypeName = "date")]
        public DateTime BirthDay { get; set; }
        
        public int Gender { get; set; }
        private Helpers.BaseViewModel.Genders _GenderShow { get; set; }
        [NotMapped]
        public Helpers.BaseViewModel.Genders GenderShow {
            get => (Helpers.BaseViewModel.Genders)Gender;
            set {
                _GenderShow = (Helpers.BaseViewModel.Genders)Gender;
            }
        }
        public int DepartmentId { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Employees")]
        public virtual Departments Department { get; set; }
        [InverseProperty("Boss")]
        public virtual ICollection<Departments> Departments { get; set; }
        [InverseProperty("Owner")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}