// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VodovozSPB.Models
{
    public partial class Employees
    {
        public Employees()
        {
            Departments = new HashSet<Departments>();
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public DateTime? BirthDay { get; set; }
        public int Gender { get; set; }
        public int Department { get; set; }

        public virtual Departments DepartmentNavigation { get; set; }
        public virtual ICollection<Departments> Departments { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}