// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VodovozSPB.Models
{
    public partial class Orders
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Partner { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOrder { get; set; }
        public int OwnerId { get; set; }

        [ForeignKey(nameof(OwnerId))]
        [InverseProperty(nameof(Employees.Orders))]
        public virtual Employees Owner { get; set; }
    }
}