// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VodovozSPB.Models
{
    public partial class Orders
    {
        public int Id { get; set; }
        public string Partner { get; set; }
        public DateTime DateOrder { get; set; }
        public int OwnerId { get; set; }

        public virtual Employees Owner { get; set; }
    }
}